### ISSUE TITLE
Home Button Plz

### ISSUE THREAD

**Issue by nglthisme** [ChrisIsEditing/chribswebsite#2]
Yo
On bottomless pages the home button is inaccessible. It would be convenient to have a button or hyperlink at the home to return to home page.
Thank you.

**Comment by ChrisIsEditing** [comment]
This will be done at a later time, and is on the todo list, closing this for now.

**Comment by ChrisIsEditing** [comment]
This has been slowly added, and will continue to be slowly added :)
